# Generated by Django 4.1 on 2022-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sentiment',
            new_name='sentimentClass',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sentiment',
            new_name='sentimentClass',
        ),
        migrations.AddField(
            model_name='comment',
            name='sentimentScore',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='sentimentScore',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
    ]
