# Generated by Django 4.1 on 2022-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0006_rename_sentiment_comment_sentimentclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
